//
// Created by mathe on 24/11/2021.
//

#ifndef PROJETCLUEDO_GROUPE3F_SAUVETAGE_INITIALISATION_H
#define PROJETCLUEDO_GROUPE3F_SAUVETAGE_INITIALISATION_H

enum {
    OUVERTURE,
    MENU,
    NOUVELLEPARTIE,
    DEMANDE_NB_JOUEUR,
    SAISIE_DES_JOUEURS,
    AIDE,
    CHOIX_DE_PARTIE_SAUVEGRARDEES,
    QUITTER_LE_JEU,
};

enum {
    INITIALISATION,
    AFFICHER_PLATEAU,
    DEBUT_TOUR,
    JOUER,
    LANCER_DE,
    ACCUSER,
    SOUPCONNER,
    VOIR_SES_CARTES,
    VICTOIRE,
    DEFAITE
};
#endif //PROJETCLUEDO_GROUPE3F_SAUVETAGE_INITIALISATION_H
